[package]
name = "bevy_nested_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = 'https://github.com/louisgjohnson/bevy', branch ='text-wrapping'}